django_portfolio/django_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls')),
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

django_portfolio/notes/urls.py
from django.urls import path
from . import views
from .views import NoteList, NoteCreate, NoteUpdate

app_name = 'notes'

urlpatterns = [
    path('notes/test/', views.test, name='test'),
    path('notes/', NoteList.as_view(), name='notes'),
    path('notes/add/', NoteCreate.as_view(), name='add_note'),
    path('notes/edit/<int:pk>', NoteUpdate.as_view(), name='edit_note'),
    path('notes/delete/<int:pk>', views.delete_note, name='delete_note'),
    path('notes/lists/', views.lists, name='lists'),
    path('notes/lists/add/', views.add_list, name='add_list'),
    path('notes/lists/edit/<int:pk>', views.edit_list, name='edit_list'),
    path('notes/lists/delete/<int:pk>', views.delete_list, name='delete_list'),
]

django_portfolio/tasks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import TaskList, TaskCreate, TaskUpdate # , delete_subtask

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', RedirectView.as_view(url='tasks/', permanent=True)),
    path('register/', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),
    path('tasks/test/', views.test, name='test'),
    path('tasks/', TaskList.as_view(), name='tasks'),
    path('tasks/add/', TaskCreate.as_view(), name='add_task'),
    path('tasks/edit/<int:pk>', TaskUpdate.as_view(), name='edit_task'),
    # path('tasks/subtasks/delete/<int:pk>/', delete_subtask, name='delete_subtask'),
    path('tasks/delete/<int:pk>', views.delete_task, name='delete_task'),
    path('tasks/lists/', views.lists, name='lists'),
    path('tasks/lists/add/', views.add_list, name='add_list'),
    path('tasks/lists/edit/<int:pk>', views.edit_list, name='edit_list'),
    path('tasks/lists/delete/<int:pk>', views.delete_list, name='delete_list'),
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Enable the serving of static files during development
]

django_portfolio/tasks/models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class TaskLists(models.Model):
    name = models.CharField(max_length=25, blank=False, null=False)
    color = models.CharField(max_length=7, default='#FFFFFF', blank=False, null=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    class Meta:
        ordering = ['owner', 'name']
    def get_absolute_url(self):
        return reverse('tasks:edit_list', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'

class Tasks(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    list = models.ForeignKey(TaskLists, on_delete=models.CASCADE, blank=False, null=False)
    date = models.DateField(blank=True, null=True)
    starred = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    details = models.CharField(max_length=1000, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    class Meta:
        ordering = ['owner', 'list', 'title']
    def get_absolute_url(self):
        return reverse('tasks:edit_task', args=[str(self.id)])
    def __str__(self):
        return f'{self.owner} | {self.list} | {self.title}'
    @property
    def is_overdue(self):
        return bool(self.date and date.today() > self.date and self.completed == False)

class Subtasks(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE, blank=False, null=False)
    completed = models.BooleanField(default=False)
    class Meta:
        ordering = ['task', 'title']
    def get_absolute_url(self):
        return reverse('tasks:edit_subtask', args=[str(self.id)])
    def __str__(self):
        return f'{self.task} | {self.title}'

django_portfolio/tasks/forms.py
from django import forms
from django.forms import inlineformset_factory, ModelForm, SelectDateWidget, Textarea
from .models import TaskLists, Tasks, Subtasks

class ListForm(ModelForm):
    class Meta:
        model = TaskLists
        fields = '__all__'
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'}),
            'owner': forms.TextInput(attrs={'readonly': True}),
        }

class TaskForm(ModelForm):
    class Meta:
        model = Tasks
        fields = '__all__'
        widgets = {
            'details': Textarea(attrs={'cols': 40, 'rows': 10}),
            'date': SelectDateWidget(),
            'owner': forms.TextInput(attrs={'readonly': True}),
        }
    def __init__(self, user, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        if user!=None:
            if user.is_superuser:
                self.fields['list'].queryset = TaskLists.objects.all()
            else:
                self.fields['list'].queryset = TaskLists.objects.filter(owner__exact=user)
            self.fields['owner'].initial = user

class SubtaskForm(ModelForm):
    class Meta:
        model = Subtasks
        fields = '__all__'

SubtaskFormSet = inlineformset_factory(
    Tasks, Subtasks, form=SubtaskForm,
    extra=0, can_delete=True, can_delete_extra=True
)

django_portfolio/tasks/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from .models import TaskLists, Tasks
from .forms import ListForm, TaskForm, SubtaskFormSet


def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render())


def register(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user_obj = form.save()
        return redirect('/accounts/login')
    context = {'form': form}
    return render(request, 'registration/register.html', context)


@login_required
def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect(request.GET.get('next'))
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'registration/change_password.html', context)


@login_required
def test(request):
    template = loader.get_template('tasks_test.html')
    context = {
        'fruits_data': ['Apple', 'Banana', 'Cherry'],
    }
    return HttpResponse(template.render(context, request))


@login_required
def lists(request):
    superuser = request.user.is_superuser
    if superuser==True:
        lists_data = TaskLists.objects.all()
    else:
        lists_data = TaskLists.objects.filter(owner__exact=request.user.id)
    paginator = Paginator(lists_data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'lists_data': lists_data,
        'superuser': superuser,
        'page_obj': page_obj,
    }
    return render(request, 'tasks_lists.html', context)


@login_required
def add_list(request):
    form = ListForm(initial={'owner': request.user.id})
    if request.method=='POST':
        form = ListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:lists')
    context = {'form': form}
    return render(request, 'tasks_add_list.html', context)


@login_required
def edit_list(request, pk):
    lists_data = get_object_or_404(TaskLists, pk=pk)
    superuser = request.user.is_superuser
    if lists_data.owner.id!=request.user.id and superuser==False:
        return redirect('tasks:lists')
    form = ListForm(instance=lists_data)
    if request.method=='POST':
        form = ListForm(request.POST, instance=lists_data)
        if form.is_valid():
            form.save()
            return redirect('tasks:lists')
    context = {'form': form}
    return render(request, 'tasks_edit_list.html', context)


@login_required
def delete_list(request, pk):
    lists_data = get_object_or_404(TaskLists, pk=pk)
    superuser = request.user.is_superuser
    if lists_data.owner.id==request.user.id or superuser==True:
        lists_data.delete()
    return redirect('tasks:lists')


class TaskList(LoginRequiredMixin, ListView):
    paginate_by = 10
    def get_queryset(self):
        superuser = self.request.user.is_superuser
        if superuser==True:
            return Tasks.objects.all()
        else:
            return Tasks.objects.filter(owner__exact=self.request.user.id)
    template_name = 'tasks_tasks.html'
    context_object_name = 'tasks_data'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['superuser'] = self.request.user.is_superuser
        return context


class TaskInline(LoginRequiredMixin):
    form_class = TaskForm
    model = Tasks
    template_name = 'tasks_add_edit_task.html'

    def form_valid(self, form):
        # if form.instance.owner is None:
        #     form.instance.owner = self.request.user
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))
        self.object = form.save()
        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('tasks:tasks')

    def formset_subtasks_valid(self, formset):
        """
        Hook for custom formset saving.Useful if you have multiple formsets
        """
        subtasks = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this 2 lines, if you have can_delete=True parameter 
        # set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for subtask in subtasks:
            subtask.task = self.object
            subtask.save()


class TaskCreate(TaskInline, CreateView):

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(TaskCreate, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        context['label'] = {'task_title': 'Task - Add', 'subtask_title': 'Subtask - Add', 'submit_button': 'Add Task'}
        return context

    def get_named_formsets(self):
        if self.request.method == 'GET':
            return {
                'subtasks': SubtaskFormSet(prefix='subtasks'),
            }
        else:
            return {
                'subtasks': SubtaskFormSet(self.request.POST or None, self.request.FILES or None, prefix='subtasks'),
            }


class TaskUpdate(TaskInline, UpdateView):

    def get(self, *args, **kwargs):
        get_return = super(TaskUpdate, self).get(*args, **kwargs)
        owner_id = self.get_object().owner.id
        logged_in_user_id = self.request.user.id
        superuser = self.request.user.is_superuser
        if owner_id!=logged_in_user_id and superuser==False:
            return redirect('tasks:tasks')
        return get_return

    def post(self, *args, **kwargs):
        post_return = super(TaskUpdate, self).post(*args, **kwargs)
        owner_id = self.get_object().owner.id
        logged_in_user_id = self.request.user.id
        superuser = self.request.user.is_superuser
        if owner_id!=logged_in_user_id and superuser==False:
            return redirect('tasks:tasks')
        return post_return

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(TaskUpdate, self).get_context_data(**kwargs)
        context['named_formsets'] = self.get_named_formsets()
        context['label'] = {'task_title': 'Task - Edit', 'subtask_title': 'Subtask - Edit', 'submit_button': 'Save Changes'}
        return context

    def get_named_formsets(self):
        return {
            'subtasks': SubtaskFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='subtasks'),
        }


@login_required
def delete_task(request, pk):
    tasks_data = get_object_or_404(Tasks, pk=pk)
    superuser = request.user.is_superuser
    if tasks_data.owner.id==request.user.id or superuser==True:
        tasks_data.delete()
    return redirect('tasks:tasks')


# '''This function is for custom added delete button functionality. If you don't want to use custom delete buttons than don't add this'''

# @login_required
# def delete_subtask(request, pk):
#     try:
#         subtask = Subtasks.objects.get(id=pk)
#     except Subtask.DoesNotExist:
#         messages.success(
#             request, 'Object Does not exit'
#             )
#         return redirect('tasks:update_task', pk=subtask.task.id)

#     subtask.delete()
#     messages.success(
#             request, 'Subtask deleted successfully'
#             )
#     return redirect('tasks:update_task', pk=subtask.task.id)

django_portfolio/tasks/templates/index.html
<!-- index.html -->


{% extends "master.html" %}


{% block title %}Tasks - Index{% endblock %}


{% block content %}

  <h1>Tasks - Index</h1>

  <p><a href="{% url 'tasks:tasks' %}">Tasks</a></p>

{% endblock %}

django_portfolio/tasks/templates/lists.html
<!-- lists.html -->


{% extends "master.html" %}


{% block title %}Lists{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      {% comment %} width: 100%; {% endcomment %}
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Lists</h1>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'tasks:add_list' %}'">Add List</button></p>

  {% if lists_data %}
    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Name</th>
        <th style="text-align:center">Color</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% for list_data in lists_data %}
      <tr>
        {% if superuser %}
          <td>{{ list_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ list_data.get_absolute_url }}">{{ list_data.name }}</a></td>
        <td style="background-color:{{ list_data.color }}80"></td>
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ list_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'tasks:delete_list' list_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No lists found.</p>
  {% endif %}

{% endblock %}

django_portfolio/tasks/templates/master.html
<!-- master.html -->


<!DOCTYPE html>
<html lang="en">


<head>

  <title>{% block title %}{% endblock %}</title>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous">

  {% load static %}
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <!-- Colorfield -->
  <script src="{% static 'colorfield/jscolor/jscolor.js' %}"></script>
  <script src="{% static 'colorfield/colorfield.js' %}"></script>

  {% block head %}{% endblock %}

</head>


<body>
  <div class="container-fluid">
    <div class="row">

      <div class="col-sm-2">
        <ul style="margin-top:20px;padding:0;list-style:none">
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
          {% endif %}
        </ul>
        <p><button style="background-color:SlateBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'tasks:tasks' %}'">Tasks</button></p>
        <p><button style="background-color:SlateBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'tasks:lists' %}'">Lists</button></p>
      </div>

      <div class="col-sm-10 ">
        {% block content %}{% endblock %}
      </div>

    </div>
  </div>
</body>


</html>

django_portfolio/tasks/templates/tasks.html
<!-- tasks.html -->


{% extends "master.html" %}


{% block title %}Tasks{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      {% comment %} width: 100%; {% endcomment %}
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Tasks</h1>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'tasks:add_task' %}'">Add Task</button></p>

  {% if tasks_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Title</th>
        <th style="text-align:center">List</th>
        <th style="text-align:center">Date</th>
        <th style="text-align:center">Starred</th>
        <th style="text-align:center">Completed</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% for task_data in tasks_data %}
      <tr>
        {% if superuser %}
          <td>{{ task_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ task_data.get_absolute_url }}">{{ task_data.title }}</a></td>
        <td style="background-color:{{ task_data.list.color }}80">{{ task_data.list }}</td>
        {% if task_data.is_overdue %}
          <td style="text-align:center;color:Tomato">{{ task_data.date|date:"d/m/Y" }}</td>
        {% else %}
          <td style="text-align:center">{{ task_data.date|date:"d/m/Y" }}</td>
        {% endif %}
        {% if task_data.starred == True %}
          <td style="text-align:center">&#11088;</td>
        {% else %}
          <td></td>
        {% endif %}
        {% if task_data.completed == True %}
          <td style="text-align:center">&#9989;</td>
        {% else %}
          <td></td>
        {% endif %}
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ task_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'tasks:delete_task' task_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    {% comment %}
    {% if is_paginated %}
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {% endif %}
    {% endcomment %}

  {% else %}

    <p>No tasks found.</p>

  {% endif %}

{% endblock %}

django_portfolio/tasks/templates/tasks_add_list.html
<!-- tasks_add_list.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'tasks:lists' %}">Task Lists</a></p>

  <br><h1>Task Lists - Add</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Add Task List</button>
  </form>

{% endblock %}

django_portfolio/tasks/templates/tasks_edit_list.html
<!-- tasks_edit_list.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'tasks:lists' %}">Task Lists</a></p>

  <br><h1>Task Lists - Edit</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Save Changes</button>
  </form>

{% endblock %}

django_portfolio/tasks/templates/tasks_lists.html
<!-- tasks_lists.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Task Lists</h1><br>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'tasks:add_list' %}'">Add Task List</button></p>

  {% if lists_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Name</th>
        <th style="text-align:center">Color</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% comment %} {% for list_data in lists_data %} {% endcomment %}
      {% for list_data in page_obj %}
      <tr>
        {% if superuser %}
          <td>{{ list_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ list_data.get_absolute_url }}">{{ list_data.name }}</a></td>
        <td style="background-color:{{ list_data.color }}80"></td>
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ list_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'tasks:delete_list' list_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    <p>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </p>

  {% else %}

    <p>No lists found.</p>

  {% endif %}

{% endblock %}

django_portfolio/tasks/templates/tasks_tasks.html
<!-- tasks_tasks.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Tasks</h1><br>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'tasks:add_task' %}'">Add Task</button></p>

  {% if tasks_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Title</th>
        <th style="text-align:center">List</th>
        <th style="text-align:center">Date</th>
        <th style="text-align:center">Starred</th>
        <th style="text-align:center">Completed</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% for task_data in tasks_data %}
      <tr>
        {% if superuser %}
          <td>{{ task_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ task_data.get_absolute_url }}">{{ task_data.title }}</a></td>
        <td style="background-color:{{ task_data.list.color }}80">{{ task_data.list }}</td>
        {% if task_data.is_overdue %}
          <td style="text-align:center;color:Tomato">{{ task_data.date|date:"d/m/Y" }}</td>
        {% else %}
          <td style="text-align:center">{{ task_data.date|date:"d/m/Y" }}</td>
        {% endif %}
        {% if task_data.starred == True %}
          <td style="text-align:center">&#11088;</td>
        {% else %}
          <td></td>
        {% endif %}
        {% if task_data.completed == True %}
          <td style="text-align:center">&#9989;</td>
        {% else %}
          <td></td>
        {% endif %}
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ task_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'tasks:delete_task' task_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    <p>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </p>

  {% else %}

    <p>No tasks found.</p>

  {% endif %}

{% endblock %}

django_portfolio/tasks/templates/tasks_test.html
<!-- tasks_test.html -->

<!DOCTYPE html>
<html>

<head>
  <title>Test</title>
</head>

<body>

  {% for fruit_data in fruits_data %}
    <h1>{{ fruit_data }}</h1>
  {% endfor %}

  <p>In views.py you can see what the fruits variable looks like.</p>

</body>
</html>