django_portfolio/django_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls')),
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

django_portfolio/notes/urls.py
from django.urls import path
from . import views
from .views import NoteList, NoteCreate, NoteUpdate

app_name = 'notes'

urlpatterns = [
    path('notes/test/', views.test, name='test'),
    path('notes/', NoteList.as_view(), name='notes'),
    path('notes/add/', NoteCreate.as_view(), name='add_note'),
    path('notes/edit/<int:pk>', NoteUpdate.as_view(), name='edit_note'),
    path('notes/delete/<int:pk>', views.delete_note, name='delete_note'),
    path('notes/lists/', views.lists, name='lists'),
    path('notes/lists/add/', views.add_list, name='add_list'),
    path('notes/lists/edit/<int:pk>', views.edit_list, name='edit_list'),
    path('notes/lists/delete/<int:pk>', views.delete_list, name='delete_list'),
]

django_portfolio/notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

class NoteLists(models.Model):
    name = models.CharField(max_length=25, blank=False, null=False)
    color = models.CharField(max_length=7, default='#FFFFFF', blank=False, null=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    class Meta:
        ordering = ['owner', 'name']
    def get_absolute_url(self):
        return reverse('notes:edit_list', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'

class Notes(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    list = models.ForeignKey(NoteLists, on_delete=models.CASCADE, blank=False, null=False)
    starred = models.BooleanField(default=False)
    note = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    class Meta:
        ordering = ['owner', 'list', 'title']
    def get_absolute_url(self):
        return reverse('notes:edit_note', args=[str(self.id)])
    def __str__(self):
        return f'{self.owner} | {self.list} | {self.title}'

django_portfolio/notes/forms.py
from django import forms
from django.forms import ModelForm
from .models import NoteLists, Notes

class ListForm(ModelForm):
    class Meta:
        model = NoteLists
        fields = '__all__'
        widgets = {
            'color': forms.TextInput(attrs={'type': 'color'}),
            'owner': forms.TextInput(attrs={'readonly': True}),
        }

class NoteForm(ModelForm):
    class Meta:
        model = Notes
        fields = '__all__'
        widgets = {
            'owner': forms.TextInput(attrs={'readonly': True}),
        }
    def __init__(self, user=None, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)
        if user!=None:
            if user.is_superuser:
                self.fields['list'].queryset = NoteLists.objects.all()
            else:
                self.fields['list'].queryset = NoteLists.objects.filter(owner__exact=user)
            self.fields['owner'].initial = user

django_portfolio/notes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from .models import NoteLists, Notes
from .forms import ListForm, NoteForm


@login_required
def test(request):
    template = loader.get_template('notes_test.html')
    context = {
        'fruits_data': ['Apple', 'Banana', 'Cherry'],
    }
    return HttpResponse(template.render(context, request))


@login_required
def lists(request):
    superuser = request.user.is_superuser
    if superuser==True:
        lists_data = NoteLists.objects.all()
    else:
        lists_data = NoteLists.objects.filter(owner__exact=request.user.id)
    paginator = Paginator(lists_data, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'lists_data': lists_data,
        'superuser': superuser,
        'page_obj': page_obj,
    }
    return render(request, 'notes_lists.html', context)


@login_required
def add_list(request):
    form = ListForm(initial={'owner': request.user.id})
    if request.method=='POST':
        form = ListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('notes:lists')
    context = {'form': form}
    return render(request, 'notes_add_list.html', context)


@login_required
def edit_list(request, pk):
    lists_data = get_object_or_404(NoteLists, pk=pk)
    superuser = request.user.is_superuser
    if lists_data.owner.id!=request.user.id and superuser==False:
        return redirect('notes:lists')
    form = ListForm(instance=lists_data)
    if request.method=='POST':
        form = ListForm(request.POST, instance=lists_data)
        if form.is_valid():
            form.save()
            return redirect('notes:lists')
    context = {'form': form}
    return render(request, 'notes_edit_list.html', context)


@login_required
def delete_list(request, pk):
    lists_data = get_object_or_404(NoteLists, pk=pk)
    superuser = request.user.is_superuser
    if lists_data.owner.id==request.user.id or superuser==True:
        lists_data.delete()
    return redirect('notes:lists')


class NoteList(LoginRequiredMixin, ListView):

    paginate_by = 10
    template_name = 'notes_notes.html'
    context_object_name = 'notes_data'

    def get_queryset(self):
        superuser = self.request.user.is_superuser
        if superuser==True:
            return Notes.objects.all()
        else:
            return Notes.objects.filter(owner__exact=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['superuser'] = self.request.user.is_superuser
        return context


class NoteCreate(LoginRequiredMixin, CreateView):

    model = Notes
    template_name = 'notes_add_note.html'
    form_class = NoteForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('notes:notes')


class NoteUpdate(LoginRequiredMixin, UpdateView):

    model = Notes
    template_name = 'notes_edit_note.html'
    form_class = NoteForm

    def get(self, *args, **kwargs):
        get_return = super(NoteUpdate, self).get(*args, **kwargs)
        owner_id = self.get_object().owner.id
        logged_in_user_id = self.request.user.id
        superuser = self.request.user.is_superuser
        if owner_id!=logged_in_user_id and superuser==False:
            return redirect('notes:notes')
        return get_return

    def post(self, *args, **kwargs):
        post_return = super(NoteUpdate, self).post(*args, **kwargs)
        owner_id = self.get_object().owner.id
        logged_in_user_id = self.request.user.id
        superuser = self.request.user.is_superuser
        if owner_id!=logged_in_user_id and superuser==False:
            return redirect('notes:notes')
        return post_return

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('notes:notes')


@login_required
def delete_note(request, pk):
    notes_data = get_object_or_404(Notes, pk=pk)
    superuser = request.user.is_superuser
    if notes_data.owner.id==request.user.id or superuser==True:
        notes_data.delete()
    return redirect('notes:notes')

django_portfolio/notes/templates/lists.html
<!-- lists.html -->


{% extends "master.html" %}


{% block title %}Note Lists{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      {% comment %} width: 100%; {% endcomment %}
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Note Lists</h1>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'notes:add_list' %}'">Add List</button></p>

  {% if lists_data %}
    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Name</th>
        <th style="text-align:center">Color</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% for list_data in lists_data %}
      <tr>
        {% if superuser %}
          <td>{{ list_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ list_data.get_absolute_url }}">{{ list_data.name }}</a></td>
        <td style="background-color:{{ list_data.color }}80"></td>
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ list_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'notes:delete_list' list_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No lists found.</p>
  {% endif %}

{% endblock %}

django_portfolio/notes/templates/notes.html
<!-- notes.html -->


{% extends "master.html" %}


{% block title %}Notes{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      {% comment %} width: 100%; {% endcomment %}
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Notes</h1>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'notes:add_note' %}'">Add Note</button></p>

  {% if notes_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Title</th>
        <th style="text-align:center">List</th>
        <th style="text-align:center">Starred</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% for note_data in notes_data %}
      <tr>
        {% if superuser %}
          <td>{{ note_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ note_data.get_absolute_url }}">{{ note_data.title }}</a></td>
        <td style="background-color:{{ note_data.list.color }}80">{{ note_data.list }}</td>
        {% if note_data.starred == True %}
          <td style="text-align:center">&#11088;</td>
        {% else %}
          <td></td>
        {% endif %}
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ note_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'notes:delete_note' note_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    {% comment %}
    {% if is_paginated %}
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {% endif %}
    {% endcomment %}

  {% else %}

    <p>No notes found.</p>

  {% endif %}

{% endblock %}

django_portfolio/notes/templates/notes_add_list.html
<!-- notes_add_list.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'notes:lists' %}">Note Lists</a></p>

  <br><h1>Note Lists - Add</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Add Note List</button>
  </form>

{% endblock %}

django_portfolio/notes/templates/notes_add_note.html
<!-- notes_add_note.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'notes:notes' %}">Notes</a></p>

  <br><h1>Notes - Add</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Add Note</button>
  </form>

{% endblock %}

django_portfolio/notes/templates/notes_edit_list.html
<!-- notes_edit_list.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'notes:lists' %}">Note Lists</a></p>

  <br><h1>Note Lists - Edit</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Save Changes</button>
  </form>

{% endblock %}

django_portfolio/notes/templates/notes_edit_note.html
<!-- notes_edit_note.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <br><p>Back to <a href="{% url 'notes:notes' %}">Notes</a></p>

  <br><h1>Notes - Edit</h1><br>

  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
      <p>
      <label>{{ field.label }}</label>
      {% if field.field.required %}
        <span style="color:red">*</span>
      {% endif %}
      {{ field }}
      {% if field.help_text %}
        <small style="color:grey">{{ field.help_text }}</small>
      {% endif %}
      </p>
      {% for error in field.errors %}
        <p style="color:red">{{ error }}</p>
      {% endfor %}
    {% endfor %}
    <button type="submit" style="background-color:Tomato;color:white;padding:10px;text-align:center;border:none;border-radius:6px">Save Changes</button>
  </form>

{% endblock %}

django_portfolio/notes/templates/notes_lists.html
<!-- notes_lists.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Note Lists</h1><br>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'notes:add_list' %}'">Add Note List</button></p>

  {% if lists_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Name</th>
        <th style="text-align:center">Color</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% comment %} {% for list_data in lists_data %} {% endcomment %}
      {% for list_data in page_obj %}
      <tr>
        {% if superuser %}
          <td>{{ list_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ list_data.get_absolute_url }}">{{ list_data.name }}</a></td>
        <td style="background-color:{{ list_data.color }}80"></td>
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ list_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'notes:delete_list' list_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    <p>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </p>

  {% else %}

    <p>No lists found.</p>

  {% endif %}

{% endblock %}

django_portfolio/notes/templates/notes_notes.html
<!-- notes_notes.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block head %}
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    tr:nth-child(even) {
      background-color: #dddddd;
    }
  </style>
{% endblock %}


{% block content %}

  <br><h1>Notes</h1><br>

  <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px" 
             onclick="document.location='{% url 'notes:add_note' %}'">Add Note</button></p>

  {% if notes_data %}

    <table>
      <tr>
        {% if superuser %}
          <th style="text-align:center">Owner</th>
        {% endif %}
        <th style="text-align:center">Title</th>
        <th style="text-align:center">List</th>
        <th style="text-align:center">Starred</th>
        <th style="text-align:center">Action</th>
      </tr>
      {% comment %} {% for note_data in notes_data %} {% endcomment %}
      {% for note_data in page_obj %}
      <tr>
        {% if superuser %}
          <td>{{ note_data.owner }}</td>
        {% endif %}
        <td><a title="Edit" href="{{ note_data.get_absolute_url }}">{{ note_data.title }}</a></td>
        <td style="background-color:{{ note_data.list.color }}80">{{ note_data.list }}</td>
        {% if note_data.starred == True %}
          <td style="text-align:center">&#11088;</td>
        {% else %}
          <td></td>
        {% endif %}
        <td style="text-align:center">
          <a title="Edit" style="text-decoration:none" href="{{ note_data.get_absolute_url }}">&#9999;&#65039;</a>
          <a title="Delete" style="text-decoration:none" href="{% url 'notes:delete_note' note_data.id %}">&#128465;&#65039;</a>
        </td>
      </tr>
      {% endfor %}
    </table>

    <p>
      <div class="pagination">
        <span class="step-links">
          {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </p>

  {% else %}

    <p>No notes found.</p>

  {% endif %}

{% endblock %}

django_portfolio/notes/templates/notes_test.html
<!-- notes_test.html -->

<!DOCTYPE html>
<html>

<head>
  <title>Test</title>
</head>

<body>

  {% for fruit_data in fruits_data %}
    <h1>{{ fruit_data }}</h1>
  {% endfor %}

  <p>In views.py you can see what the fruits variable looks like.</p>

</body>
</html>