django_portfolio/django_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tasks.urls')),
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

django_portfolio/notes/urls.py
from django.urls import path
from . import views
from .views import NoteList, NoteCreate, NoteUpdate

app_name = 'notes'

urlpatterns = [
    path('notes/test/', views.test, name='test'),
    path('notes/', NoteList.as_view(), name='notes'),
    path('notes/add/', NoteCreate.as_view(), name='add_note'),
    path('notes/edit/<int:pk>', NoteUpdate.as_view(), name='edit_note'),
    path('notes/delete/<int:pk>', views.delete_note, name='delete_note'),
    path('notes/lists/', views.lists, name='lists'),
    path('notes/lists/add/', views.add_list, name='add_list'),
    path('notes/lists/edit/<int:pk>', views.edit_list, name='edit_list'),
    path('notes/lists/delete/<int:pk>', views.delete_list, name='delete_list'),
]

django_portfolio/tasks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import RedirectView
from . import views
from .views import TaskList, TaskCreate, TaskUpdate # , delete_subtask

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', RedirectView.as_view(url='tasks/', permanent=True)),
    path('register/', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),
    path('tasks/test/', views.test, name='test'),
    path('tasks/', TaskList.as_view(), name='tasks'),
    path('tasks/add/', TaskCreate.as_view(), name='add_task'),
    path('tasks/edit/<int:pk>', TaskUpdate.as_view(), name='edit_task'),
    # path('tasks/subtasks/delete/<int:pk>/', delete_subtask, name='delete_subtask'),
    path('tasks/delete/<int:pk>', views.delete_task, name='delete_task'),
    path('tasks/lists/', views.lists, name='lists'),
    path('tasks/lists/add/', views.add_list, name='add_list'),
    path('tasks/lists/edit/<int:pk>', views.edit_list, name='edit_list'),
    path('tasks/lists/delete/<int:pk>', views.delete_list, name='delete_list'),
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Enable the serving of static files during development
]

django_portfolio/templates/index.html
<!-- index.html -->


{% extends "master.html" %}


{% block title %}Django Portfolio{% endblock %}


{% block content %}

  <h1>Tasks</h1>
  <p><a href="{% url 'tasks:tasks' %}">Tasks</a></p>

  <h1>Notes</h1>
  <p><a href="{% url 'notes:notes' %}">Notes</a></p>

{% endblock %}

django_portfolio/templates/master.html
<!-- master.html -->


{% load static %}


<!DOCTYPE html>
<html lang="en">


<head>

  <title>{% block title %}{% endblock %}</title>

  <!-- Add Bootstrap 5 to Template -->
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'styles.css' %}" />

  <!-- Favicon -->
  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

  {% block head %}{% endblock %}

</head>


<body>
  <div class="container-fluid">
    <div class="row">

      <div class="col-auto text-center">
        <br><img src="{% static 'portfolio.png' %}" alt="My image" width="50" height="50">
        <br><h5>Django Portfolio</h5>
        <ul style="margin-top:20px;padding:0;list-style:none">
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }} ({{ user.id }})</li>
            <li>
              <form method="post" action="{% url 'logout' %}?next={{ request.path }}">
                {% csrf_token %}
                <button type="submit" class="btn btn-link">Logout</button>
              </form>
            </li>
            <li><a href="{% url 'tasks:change_password' %}?next={{ request.path }}" class="btn btn-link">Change Password</a></li>
          {% else %}
            <li><a href="{% url 'login' %}" class="btn btn-link">Login</a></li>
          {% endif %}
        </ul>
        <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'tasks:tasks' %}'">Tasks</button></p>
        <p><button style="background-color:DodgerBlue;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'tasks:lists' %}'">Task Lists</button></p>
        <p><button style="background-color:MediumSeaGreen;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'notes:notes' %}'">Notes</button></p>
        <p><button style="background-color:MediumSeaGreen;color:white;padding:10px;text-align:center;border:none;border-radius:6px;width:150px"
                   onclick="document.location='{% url 'notes:lists' %}'">Note Lists</button></p>
      </div>

      <div class="col">
        {% block content %}{% endblock %}
      </div>

    </div>
  </div>
</body>


</html>